feat: a linear subtasking example in demo
aneoconsulting/ArmoniK.Samples pull request #99
Opened 2024-05-15 09:57 UTC by ereali-aneo

2024-05-15 09:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aneoconsulting/ArmoniK.Samples?pullRequest=99) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aneoconsulting/ArmoniK.Samples?pullRequest=99) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aneoconsulting/ArmoniK.Samples?pullRequest=99) it.</sub>

2024-05-15 15:26 UTC, ngruelaneo approved these changes

2024-05-15 15:26 UTC, ngruelaneo commented on csharp/native/LinearSubTasking/Client/Dockerfile
> +#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.
a effacer

2024-05-15 15:26 UTC, ngruelaneo commented on csharp/native/LinearSubTasking/Client/Dockerfile
> +#ARG TNAME="ArmoniK.Samples.LinearSubTasking.Client" TPATH="SubTasking/Client/"
idem

2024-05-15 15:26 UTC, ngruelaneo commented on csharp/native/LinearSubTasking/Client/Program.cs
> +          RootCommand("Calculate the result of integer % 2 with subtask example for ArmoniK.\nIt sends a task to ArmoniK with integer in input and create a new subtask for each substraction of 2 whil
```suggestion
          RootCommand("Calculate the result of integer % 2 with subtask example for ArmoniK.\nIt sends a task to ArmoniK with integer an as input and create a new subtask. At each subtask creation the number 2 is substract to the input integer until the result is greater than 1.");
```

2024-05-16 07:20 UTC, aneojgurhem requested changes

2024-05-16 07:20 UTC, aneojgurhem commented on csharp/native/LinearSubTasking/Client/ArmoniK.Samples.LinearSubTasking.Client.csproj
> +    <ImplicitUsings>enable</ImplicitUsings>
```suggestion
```

Do not use implicit usings ! (in both projects^^)

2024-05-16 07:20 UTC, aneojgurhem commented on csharp/native/LinearSubTasking/Worker/Program.cs
> +// Create the application and register thesubmit task example worker implementation
```suggestion
// Create the application and register the submit task example worker implementation
```

2024-05-16 07:20 UTC, aneojgurhem commented on csharp/native/LinearSubTasking/Worker/appsettings.Development.json
No need for this file. Can you remove it from history ?

2024-05-16 07:20 UTC, aneojgurhem commented on csharp/native/LinearSubTasking/Client/Program.cs
> +                                 .ResultId;
Can you print this resultId ? (mainly for easier debugging when there is an issue during task execution)

2024-05-16 07:20 UTC, aneojgurhem commented on csharp/native/LinearSubTasking/Client/Program.cs
> +          RootCommand("Calculate the result of integer % 2 with subtask example for ArmoniK.\nIt sends a task to ArmoniK with integer an as input and create a new subtask. At each subtask creation th
```suggestion
          RootCommand("Calculate the result of integer % 2 with subtask example for ArmoniK.\nIt sends a task to ArmoniK with integer an as input and create a new subtask. At each subtask creation the number 2 is substracted to the input integer as long as the result is greater than 1.");
```

2024-05-16 07:20 UTC, aneojgurhem commented on csharp/native/LinearSubTasking/Worker/LinearSubTasking.cs
> +        }
Can and should be factorized a little bit

2024-05-17 08:47 UTC, closed without merging